# Generated by Django 5.0.4 on 2024-06-16 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la marca')),
                ('nombreMarca', models.CharField(max_length=50, verbose_name='Nombre de la marca')),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('idCamara', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la camara')),
                ('nombreCamara', models.CharField(max_length=50, verbose_name='Nombre de la camara')),
                ('precio', models.IntegerField(verbose_name='Precio de la camara')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion de la camara')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen de la camara')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.marca')),
            ],
        ),
    ]
