# Generated by Django 5.0.4 on 2024-06-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion de la camara'),
        ),
    ]
