# Generated by Django 5.0.4 on 2024-07-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_boleta_detalleboleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock de la camara'),
        ),
    ]
